
# =========================
# Main file for Elinsz Code Editor
#
# by Elio Inoc. Souza, www.elinsz3d.com.br, mail@suporte.elinsz3d.com.br
#
# DO NOT EDIT THIS FILE IN THE Elinsz, IT WILL STRIP SOME OF THE CODE!!!
# =========================

require 'sketchup.rb'
require 'fileutils'
#require_relative 'ActivationDialog'  # Adiciona o require da ActivationDialog.rb


## =====================

module EIS_Extensions

  module ELINSZ3DS
  PLUGIN_NAME = "ELINSZ 3DS"
  COMPONENT_DIR = File.join(__dir__, "componentes")


    # Creates new class

      class Elinsz3ds < UI::WebDialog

        # Initialize class and callbacks
        def initialize
          ## =====================
          ## Chamar a ativação antes de abrir a UI principal

          ## activation = EIS_Extensions::EIS_Elinsz::ActivationDialog.new
          ## return unless activation.activated?  # Bloqueia o acesso se não estiver ativado

          ## =====================

          ## Set some variables

          # Get this file's directory w/ backcomp for "//" in file path
          @base_dir = File.dirname(__FILE__).gsub(%r{//}) { "/" }

          # Get user directory
          @user_dir = (ENV['USERPROFILE'] != nil) ? ENV['USERPROFILE'] :
            ((ENV['HOME'] != nil) ? ENV['HOME'] : @base_dir )

          # Get working directory from last file - set to user directory otherwise
          @last_file = Sketchup.read_default "elinsz_3ds", "last_file"
          @last_file != nil ? @snip_dir = File.dirname(@last_file) : @snip_dir = @user_dir


          ## =====================

          ## Set up the WebDialog interface

          # Dialog parameters
          super "Elinsz 3DS", false, "Elinsz 3DS", 750, 600, 100, 100, true

          # Set HTML UI file for WebDialog
          ui_loc = File.join( @base_dir , "interface.html" )
          set_file( ui_loc )
          navigation_buttons_enabled = false
          min_width = 500
          min_height = 500


          ## =====================

          ## Show the dialog and run the new routine

          show do

            # Set version number in about dlg
            execute_script("var rceVersion = #{Elinsz3ds::EXTVERSION.to_s}")
            execute_script("$('#version').text( rceVersion )")

            Sketchup.status_text = "#{Elinsz3ds::EXTTITLE} | Welcome!"

          end  # show


          ## =====================

          ## Offer a save when dialog closes

          set_on_close do

            # Some feedback
            execute_script("addResults('Closing editor...')")

            # Handling closing confirmation in RB rather than JS
            r = UI.messagebox "Save this file before quitting?", MB_YESNO

            if r == 6 then

              execute_script("cb_save()")

            end

            Sketchup.status_text = "#{ELINSZ3DS::EXTTITLE} | Bye!"

          end  # set_on_close

          ## =====================

        end # initialize

    end # class Elinsz3ds


## ================================================================

    ## Show local or remote website either as a WebDialog or HtmlDialog

    def self.browser( title , loc , isfile = false )

      if Sketchup.version.to_f < 17 then  # Use old WebDialog method
        @dlg = UI::WebDialog.new( title , true ,
          title.gsub(/\s+/, "_") , 1000 , 600 , 100 , 100 , true);
        @dlg.navigation_buttons_enabled = false
        isfile ? @dlg.set_file( loc ) : @dlg.set_url( loc )
        @dlg.show
      else  # Use new HtmlDialog
        @dlg = UI::HtmlDialog.new( { :dialog_title => title, :width => 1000, :height => 600,
          :style => UI::HtmlDialog::STYLE_DIALOG, :preferences_key => title.gsub(/\s+/, "_") } )
        isfile ? @dlg.set_file( loc ) : @dlg.set_url( loc )
        @dlg.show
        @dlg.center
      end

    end  # def self.browser


    ## =====================

## Add menu items

unless file_loaded?(__FILE__)

  # Add main menu items
  sub = UI.menu("Window").add_submenu("Elinsz 3DS")
  sub.add_item("Menu Principal") { editordlg = ELINSZ3DS::Elinsz3ds.new }
  # sub.add_item("OpComponentes") { editordlg = EIS_OpComponentes::OpComponentes.new }

  ## Add menu items
  # Criar toolbar
  as_rce_tb = UI::Toolbar.new "Elinsz 3DS"

  # ÍCONE ESTÁTICO (Apenas visual)
  logo_cmd = UI::Command.new("Logo") { }  # Sem ação ao clicar
  logo_cmd.small_icon = "img/elinsz.svg"  # Ícone da empresa
  logo_cmd.large_icon = "img/elinsz.svg"
  logo_cmd.tooltip = "Plugin Elinsz 3D"
  logo_cmd.status_bar_text = "Logo da empresa"
  as_rce_tb.add_item logo_cmd

  # Adicionar separador
  as_rce_tb.add_separator

  Botão interativo - Elinsz 3DS
  elinsz_cmd = UI::Command.new("Elinsz 3DS") { editordlg = ELINSZ3DS::Elinsz3ds.new unless editordlg }
  elinsz_cmd.small_icon = "img/elinsz-2.svg"
  elinsz_cmd.large_icon = "img/elinsz-2.svg"
  elinsz_cmd.tooltip = "Menu Principal"
  elinsz_cmd.status_bar_text = "Projeto paramétrico para sistemas Modulares"
  as_rce_tb.add_item elinsz3ds_cmd

  # Adicionar separador
  # as_rce_tb.add_separator

  #   # Botão interativo - Usinagem
  #   usinagem_cmd = UI::Command.new("Usinagem") { editordlg = EIS_Usinagem::Usinagem.new unless editordlg }
  #   usinagem_cmd.small_icon = "img/tools.svg"
  #   usinagem_cmd.large_icon = "img/tools.svg"
  #   usinagem_cmd.tooltip = "Configurador de Usinagens"
  #   usinagem_cmd.status_bar_text = "Configuração de Usinagens e Ferramentas"
  #   as_rce_tb.add_item usinagem_cmd

  # Adicionar separador
  # as_rce_tb.add_separator

  #   # Botão interativo - CutList
  #   atributos_cmd = UI::Command.new("CutList") { editordlg = EIS_CutList::CutList.new unless editordlg }
  #   atributos_cmd.small_icon = "img/attributes.svg"
  #   atributos_cmd.large_icon = "img/attributes.svg"
  #   atributos_cmd.tooltip = "CutList"
  #   atributos_cmd.status_bar_text = "Gerenciador de Plano de Cortes"
  #   as_rce_tb.add_item atributos_cmd


  # Exibir toolbar
  # as_rce_tb.show

  #   # Add main menu items
  #   # Criar toolbar
  #   as_rce_tb = UI::Toolbar.new "New toolbars-Elinsz 3DS"
  #   # sub = UI.menu("Window").add_submenu("Elinsz 3D")


  #   # Botão interativo - OpComponentes
  #   opComponentes_cmd = UI::Command.new("OpComponentes") { editordlg = EIS_OpComponentes::OpComponentes.new unless editordlg }
  #   opComponentes_cmd.small_icon = "img/OpComponente.svg"
  #   opComponentes_cmd.large_icon = "img/OpComponente.svg"
  #   opComponentes_cmd.tooltip = "Opção de Componentes"
  #   opComponentes_cmd.status_bar_text = "Opção de Componentes"
  #   as_rce_tb.add_item opComponentes_cmd

  # Adicionar separador
  # as_rce_tb.add_separator


  #   # Botão interativo - Atributos
  #   atributos_cmd = UI::Command.new("Atributos") { editordlg = EIS_Atributos::Atributos.new unless editordlg }
  #   atributos_cmd.small_icon = "img/attributes.svg"
  #   atributos_cmd.large_icon = "img/attributes.svg"
  #   atributos_cmd.tooltip = "Configurador Atributos"
  #   atributos_cmd.status_bar_text = "Atributos para sistemas de Módulos"
  #   as_rce_tb.add_item atributos_cmd

  # Adicionar separador
  # as_rce_tb.add_separator

  #   # Botão interativo - Usinagem
  #   relatorios_cmd = UI::Command.new("Relatorios") { editordlg = EIS_Relatorios::Relatorios.new unless editordlg }
  #   relatorios_cmd.small_icon = "img/rerun.svg"
  #   relatorios_cmd.large_icon = "img/rerun.svg"
  #   relatorios_cmd.tooltip = "Gerador de Relatorios"
  #   relatorios_cmd.status_bar_text = "Configuração de Usinagens e Ferramentas"
  #   as_rce_tb.add_item relatorios_cmd

  # as_rce_tb.show

  # Indicar que o arquivo foi carregado
  file_loaded(__FILE__)

end  # unless

end  # module ELINSZ3DS

end  # module EIS_Extensions
